### ISSUE TITLE
Unable to connect kairosdb datasource

### ISSUE THREAD

**Issue by RamakrishnaAddanki** [Kratos-ISE/birt-kairosdb-datasource-plugin#2]
Hi folks,

I am unable to connect to kairosdb datasource can you please help me out over here the following is the error i am getting 
i am using JDK 7 version in eclipse 

org.eclipse.datatools.connectivity.oda.consumer.helper.OdaHelperException: Unable to load or instantiate the custom ODA driver class. (com.kratos.birt.report.data.oda.kairosdb.impl.Driver) ; org.eclipse.datatools.connectivity.oda.OdaException ;
ava.lang.ClassNotFoundException: com.kratos.birt.report.data.oda.kairosdb.impl.Driver cannot be found by com.kratos.birt.report.data.oda.kairosdb_1.0.1.qualifier

	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaDriver.loadDriverInstance(OdaDriver.java:251)

	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaDriver.init(OdaDriver.java:198)

	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaDriver.<init>(OdaDriver.java:74)

	at org.eclipse.datatools.connectivity.oda.profile.OdaConnectionWrapper.getOdaDriverHelper(OdaConnectionWrapper.java:236)

	at org.eclipse.datatools.connectivity.oda.profile.OdaConnectionWrapper.getOdaConnectionHelper(OdaConnectionWrapper.java:225)

	at org.eclipse.datatools.connectivity.oda.profile.OdaConnectionWrapper.<init>(OdaConnectionWrapper.java:57)

	at org.eclipse.datatools.connectivity.oda.profile.OdaConnectionFactory.createConnection(OdaConnectionFactory.java:26)

	at org.eclipse.datatools.connectivity.internal.ConnectionFactoryProvider.createConnection(ConnectionFactoryProvider.java:83)

	at org.eclipse.datatools.connectivity.internal.ConnectionProfile.createConnection(ConnectionProfile.java:359)

	at org.eclipse.datatools.connectivity.ui.PingJob.createTestConnection(PingJob.java:76)

	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSourceWizardPageCore$1.run(DataSourceWizardPageCore.java:244)

	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)

	at org.eclipse.datatools.connectivity.ui.wizards.ConnectionProfileDetailsPage.testConnection(ConnectionProfileDetailsPage.java:194)

	at org.eclipse.datatools.connectivity.ui.wizards.ConnectionProfileDetailsPage$2.widgetSelected(ConnectionProfileDetailsPage.java:131)

	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)

	at org.eclipse.jface.window.Window.open(Window.java:808)

	at org.eclipse.birt.report.designer.data.ui.actions.NewDataSourceAction.run(NewDataSourceAction.java:126)

	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)

	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)

	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)

	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)

	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)

	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)

	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)

	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)

	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)

	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)

	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)

	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)

	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)

	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)

	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

Caused by: org.eclipse.datatools.connectivity.oda.OdaException ;
    java.lang.ClassNotFoundException: com.kratos.birt.report.data.oda.kairosdb.impl.Driver cannot be found by com.kratos.birt.report.data.oda.kairosdb_1.0.1.qualifier

	at org.eclipse.datatools.connectivity.oda.consumer.helper.DriverExtensionHelper.loadDriverClass(DriverExtensionHelper.java:134)

	at org.eclipse.datatools.connectivity.oda.consumer.helper.OdaDriver.loadDriverInstance(OdaDriver.java:224)

	... 52 more

Caused by: java.lang.ClassNotFoundException: com.kratos.birt.report.data.oda.kairosdb.impl.Driver cannot be found by com.kratos.birt.report.data.oda.kairosdb_1.0.1.qualifier

	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:336)

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:328)

	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:568)

	at org.eclipse.datatools.connectivity.oda.consumer.helper.DriverExtensionHelper.loadDriverClass(DriverExtensionHelper.java:129)

	... 53 more

**Comment by rdettai** [comment]
Hi ! Could you please specify:

**Comment by RamakrishnaAddanki** [comment]
Hi Thanks for your reply 
I have downloaded eclipse from this link which is provided by this repo documentation.
https://www.eclipse.org/downloads/packages/eclipse-ide-java-and-report-developers/lunar 

eclipse.ini file 
-startup
plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.200.v20140603-1326
-product
org.eclipse.epp.package.reporting.product
--launcher.defaultAction
openFile
--launcher.XXMaxPermSize
256M
-showsplash
org.eclipse.platform
--launcher.XXMaxPermSize
256m
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vm
C:\Program Files\Java\jre7\bin\server\jvm.dll
-vmargs
-Dosgi.requiredJavaVersion=1.6
-Xms40m
-Xmx512m

I have added the folders which i downloaded from this repository into dropins folder of eclipse please find attachment
![eclipse_dropins_folder](https://cloud.githubusercontent.com/assets/14921776/19587129/865da87a-9779-11e6-858b-dfcc3cb824bf.PNG)

**Comment by lcoulet** [comment]
Hello there.

You should download the binary zip file from the release and place the jar files in the  dropin folder: [releases/tag/v1.0.0](https://github.com/Kratos-ISE/birt-kairosdb-datasource-plugin/releases/tag/v1.0.0)

Is that what you did?

**Comment by RamakrishnaAddanki** [comment]
Hi Icoulet,
Thanks for ur very quick reply i have added the jars from your link and it is working fine now.
